### ISSUE TITLE
maya2019

### ISSUE THREAD

**Issue by fangxingsheji** [AKEric/skinner#2]
hi ！ How to install in maya2019, get error message.
# Error: RuntimeError: file <C:\Program Files\Autodesk\Maya2019\Python\lib\site-packages\skinner\__init__.py> line 3: Marshal loads failed #

**Comment by AKEric** [comment]
https://github.com/AKEric/skinner#requirements

Skinner is only tested on Maya 2022, using Python 3.  While technically skinner could run in Maya 2019, I don't believe Maya 2019 supports Python 3.
