### ISSUE TITLE
Marshal loads failed

### ISSUE THREAD

**Issue by charliewales** [AKEric/skinner#3]
Hi, latest v1.1.8 is giving me this error. v1.1.7 was fine. Thanks for sharing. Cheers

# Error: RuntimeError: file <[...]\skinner\window.py> line 1: Marshal loads failed

**Comment by AKEric** [comment]
I've seen similar errors before:  100% of the time (so far) this means you're trying to run it in a Maya that's in Python 2.x, not 3.x

The 1.1.8 update was a single line bugfix to a print statement.  My guess would be, if you reverted back to 1.1.7 you'd see the exact same error.

Can you confirm your python version by running this in the Script Editor?

import sys
print(sys.version)

I've confirmed it works on 3.7.7 -> 3.9.7

Also: This is the 'short version' of a Maya error:  In the Script Editor, can you enable : History -> Show Line Numbers In Errors & Show Stack Trace : If this is a legit error somehow, this will give me better debug info.

**Comment by charliewales** [comment]
Umm, ok. I was testing on Maya 2023 so the python 2.x is ruled out. I tried on a fresh prefs Maya and getting the same error. The stack trace does not give any more meaningful output. I attach a couple of videos on Maya 2022.3. Thanks

https://user-images.githubusercontent.com/2865181/163122672-c6587fea-943f-415c-acf9-e37526aac6b4.mp4


https://user-images.githubusercontent.com/2865181/163122677-89ca131a-891e-4720-8802-7fad8e775b6c.mp4

.

**Comment by charliewales** [comment]
Could it be the numpy or scipy versions?

**Comment by AKEric** [comment]
Really weird, I have no explanation. Both videos are on the same machine, same Maya, just two different versions of the tool?

I recently updated the Maya beta to a new version, and I was getting a numpy/scipy import error: I had to uninstall them/reinstall them via pip, and everything started working correctly again. Not sure if this is somehow related to you too?

But like I said.... I've tested this update on multiple machines now and cannot repro your issue :S

**Comment by charliewales** [comment]
Yeah, same Maya, same machine, different versions of the tool (1.1.7 and 1.1.8), it reallt seems weird. Anyway, I'll let you know in case I find the issue. Thanks.

**Comment by tcwilsonart** [comment]
I'm just installing for the first time but experienced the same issue. 1.7 works but not 1.8. Some searching suggests it is pyarmor related.

https://pyarmor.readthedocs.io/en/latest/questions.html#marshal-loads-failed-when-running-xxx-py

**Comment by AKEric** [comment]
thanks for the feedback tcwilsonart  & that link, I'll see if that has any bearing here.

**Comment by adevra** [comment]
Same here, Maya2022 -pythonver 3

import numpy as np
import scipy as sp
print(np.__file__)
print(sp.__file__)
C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\numpy\__init__.py
C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\scipy\__init__.py

import skinner.core as skinCore
skinCore.test()
# Error: RuntimeError: file ..\skinner\__init__.py> line 3: Marshal loads failed #

**Comment by munkybutt** [comment]
Hey - I am having the same issue.
Maya 2023
skinner v1.1.8

```
import skinner.core as skcore
File "<C:\p4ws\sharkmob\Tools\tech_art\base\maya\python\_third_party\skinner\core.py>", line 1, in <module>
File "<frozen skinner.core>", line 154, in <module>
File "<C:\p4ws\sharkmob\Tools\tech_art\base\maya\python\_third_party\skinner\utils.py>", line 1, in <module>
RuntimeError: Marshal loads failed
```

**Comment by munkybutt** [comment]
Same with Maya 2022 :(

**Comment by tomadr86** [comment]
I have same issue (Maya 2022, 3.7.7 Python), any solution yet?
```
...\skinner\__init__.py>", line 3, in <module>
# RuntimeError: Marshal loads failed # 
```

**Comment by tomadr86** [comment]
1.7 version also not working for me, getting different error
```
...\skinner\utils.py>", line 1, in <module>
#   File "<frozen skinner.utils>", line 202, in <module>
# AttributeError: 'NoneType' object has no attribute 'ndarray' # 
```

**Comment by AKEric** [comment]
Thanks for the feedback:  I continue to be unable to repro this bug, and the tool is in use at multiple studios across multiple versions of Maya.    That being said:

I've been doing some digging, and I'll try and look into it over the weekend. I _think_ this has to do with how Pyarmor is obfuscating the code:  I don't use marshal in my code, but Pyarmor does.

Question to anyone with this issue: Are you on Windows? Or another OS?  I've only tested it on Windows.

However, _this_ error (tomadr86):
# AttributeError: 'NoneType' object has no attribute 'ndarray' # 

Would indicate that either numpy/scipy weren't installed correctly.  Does this code run in Maya correctly?

import numpy as np
import scipy as sp
print(np.__file__)
print(sp.__file__)

**Comment by charliewales** [comment]
![imagen](https://user-images.githubusercontent.com/2865181/211075150-2de9fe31-4141-4d8d-b47a-059205eac6f2.png)
![imagen](https://user-images.githubusercontent.com/2865181/211075172-b557d492-9458-425b-8d16-64c15acaff5b.png)
![imagen](https://user-images.githubusercontent.com/2865181/211075213-f0ee426f-8edd-43a4-a7f6-6be0482bed89.png)

**Comment by munkybutt** [comment]
> Question to anyone with this issue: Are you on Windows? Or another OS? I've only tested it on Windows.

Windows 10

**Comment by AKEric** [comment]
I've reobfuscated the modules and made a new release:https://github.com/AKEric/skinner/releases/tag/Reobfuscate

See if that fixes the bug?  I have my doubts, but since I can't repro it, it's hard to test/fix.

**Comment by charliewales** [comment]
Guess what? It worked! No more "Marshal loads failed", thank you and cheers!

Windows 10, Maya 2023.3, v1.1.8

![imagen](https://user-images.githubusercontent.com/2865181/213908461-f9e02560-d474-4380-9c70-73c6a93559de.png)

**Comment by munkybutt** [comment]
Can confirm that it works on Windows10 on 2023.
But now it doesn't work with 2022.
What version of python are you using to do the obfuscation?
I think you might have to do a specific version for 37 + 39?
Anyways, we are on 2023 and earlier releases work on 2022 so we can use them if we need to.
Thanks for trying to sort this, I appreciate it is a pain if you can't repro the issue yourself

**Comment by charliewales** [comment]
Looks like the Python version is to blame.

https://stackoverflow.com/questions/67448667/pyarmor-marshal-loads-failed
https://pyarmor.readthedocs.io/en/latest/questions.html
![imagen](https://user-images.githubusercontent.com/2865181/214076004-3922d24a-25ed-4cd5-911a-20dd7d522891.png)

**Comment by AKEric** [comment]
Sigh, I know what the issue is:  I've been misinterpreting what the above 'marshal load fails' means.

I thought it meant, the version of Python PyArmor was using to obfuscate the code was different form the version of Python the code was authored in.  

Nope.  It's that if anyone tries to run the code that isn't in the same version of Python as PyArmor was when it was obfuscated, it fails.  

which really sucks, lol.   Kind of makes me question the usefulness of PyArmor at all.  Armed with this I'll ping the dev and see if I can sort this out better. 

It also explains the reasons it works at other studios with different Maya versions : They're internal to my company and have the source, thus it's not obfuscated to them.

**Comment by AKEric** [comment]
PyArmor is becoming to difficult to work with, and their support is... not good.

I'd rather people use this tool successfully : I've just pushed the whole open source codebase with the latest package.

But I'd still appreciate $tips$ for it's usage.

Please 'buy me a coffee' per the below suggested tipping rate: https://www.buymeacoffee.com/akeric

* Student / Hobbyist / Indy dev : Free! (but if you want to donate, I won't turn you down)
* Any other production : $25 a user.

It accepts Google Pay, Apple Pay, and Credit Card.

**Comment by charliewales** [comment]
Hey Eric, that's very kind of you. To be honest I do not use in my day to day work as my rigging days are behind, I just wanted to give you feedback for your efforts. Cheers

P.S: I tried to buy you a couple of coffees (credit card) but I did not work for me (error processing)

**Comment by AKEric** [comment]
Thanks for giving it a go and the feedback ok the payment issue

"Technology" amirite?

**Comment by AKEric** [comment]
"and now accepting paypal" lol

https://paypal.me/akpavey

**Comment by charliewales** [comment]
yeah, Paypal did the trick. Enjoy your coffees! Cheers
