### ISSUE TITLE
Traceback when trying to run  on macOS

### ISSUE THREAD

**Issue by RJJ** [AKEric/skinner#5]
note: verified numpy and scipy are installed
Maya version 2022.4 macOS

Tracebacks below:
import skinner.core as skinCore
skinCore.test()
# Could not find "/Users/rjj/Library/Preferences/Autodesk/maya/2022/scripts/skinner/pytransform/platforms/darwin/x86_64/_pytransform.dylib"
# Error: 1
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "/Users/rjj/Library/Preferences/Autodesk/maya/2022/scripts/skinner/__init__.py", line 2, in <module>
#     pyarmor_runtime()
#   File "/Users/rjj/Library/Preferences/Autodesk/maya/2022/scripts/skinner/pytransform/__init__.py", line 379, in pyarmor_runtime
#     sys.exit(1)
# SystemExit: 1 # 

import skinner.window as skinWin
skinWin.App()
# Could not find "/Users/rjj/Library/Preferences/Autodesk/maya/2022/scripts/skinner/pytransform/platforms/darwin/x86_64/_pytransform.dylib"
# Error: 1
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "/Users/rjj/Library/Preferences/Autodesk/maya/2022/scripts/skinner/__init__.py", line 2, in <module>
#     pyarmor_runtime()
#   File "/Users/rjj/Library/Preferences/Autodesk/maya/2022/scripts/skinner/pytransform/__init__.py", line 379, in pyarmor_runtime
#     sys.exit(1)
# SystemExit: 1 #

**Comment by AKEric** [comment]
Now that the tool is OpenSource this should be a non issue
