### ISSUE TITLE
Error: AttributeError: file C:\Users/ASUS/Documents/maya/scripts\skinner\utils.py line 190: 'NoneType' object has no attribute 'ndarray'

### ISSUE THREAD

**Issue by Orkosara** [AKEric/skinner#6]
So i put /skinner sub directory to C:\Users\ASUS\Documents\maya\scripts and it gives me an  Error: AttributeError: file C:\Users/ASUS/Documents/maya/scripts\skinner\utils.py line 190: 'NoneType' object has no attribute 'ndarray'
 
I am using Maya 2023.3.  Why this is happening ?

**Comment by AKEric** [comment]
Apologies on missing this @Neptrone  : Still having the problem (it's been a year).

That error would indicate that numpy isn't installed / seen by Maya.  Did you follow the install docs provided?

**Comment by AKEric** [comment]
Will close this based on lack of response.
