### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by smref** [AKEric/skinner#8]
Really looking forward to using that one.  Seems to be exactly what I'm looking for.
Thanks A LOT.

Also found small typos.

![image](https://github.com/user-attachments/assets/1c18e642-cff0-4145-b333-a3ee870bf911)
![image](https://github.com/user-attachments/assets/bc431313-e578-438b-bc41-66f546cdb956)

**Comment by AKEric** [comment]
Thanks for catching the typos, appreciate!  Will fix in the next release.

**Comment by AKEric** [comment]
Fixed typo's in the 1.3.0 release, thanks for the notification.
